#![allow(dead_code)]
//! Collection Societies Registry — 150+ worldwide PROs, CMOs, and neighbouring
//! rights organisations for global royalty payout routing.
//!
//! This module provides:
//!   - A comprehensive registry of 150+ worldwide collection societies
//!   - Territory → society mapping for automatic payout routing
//!   - Right-type awareness: performance, mechanical, neighbouring, reprographic
//!   - Reciprocal agreement resolution (CISAC, BIEM, IFPI networks)
//!   - Payout instruction generation per society
//!
//! Coverage regions:
//!   - North America (11 societies)
//!   - Latin America (21 societies)
//!   - Europe (60 societies)
//!   - Asia-Pacific (22 societies)
//!   - Africa (24 societies)
//!   - Middle East (11 societies)
//!   - International bodies (6 umbrella organisations)
//!
//! Reference:
//!   - CISAC member list: https://www.cisac.org/Cisac-Services/Societies
//!   - BIEM member list: https://biem.org/members/
//!   - IFPI global network: https://www.ifpi.org/

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ── Right Type ────────────────────────────────────────────────────────────────

/// Type of right administered by a collection society.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RightType {
    /// Public performance rights (ASCAP, BMI, PRS, GEMA, SACEM…)
    Performance,
    /// Mechanical reproduction rights (MCPS, BUMA/STEMRA, GEMA, ZAIKS…)
    Mechanical,
    /// Neighbouring rights / sound recording (PPL, SoundExchange, SCPP…)
    Neighbouring,
    /// Reprographic rights (photocopying / reproduction)
    Reprographic,
    /// Private copying levy
    PrivateCopying,
    /// Synchronisation rights
    Synchronisation,
    /// All rights (combined licence)
    AllRights,
}

// ── Society Record ────────────────────────────────────────────────────────────

/// A collection society / PRO / CMO / neighboring-rights organisation.
/// NOTE: `Deserialize` is NOT derived — the registry is static; fields use
/// `&'static` references which cannot be deserialized from JSON.
#[derive(Debug, Serialize)]
pub struct CollectionSociety {
    /// Unique internal ID (e.g. "ASCAP", "GEMA", "JASRAC")
    pub id: &'static str,
    /// Full legal name
    pub name: &'static str,
    /// Country ISO 3166-1 alpha-2 codes served (primary territories)
    pub territories: &'static [&'static str],
    /// Rights administered
    pub rights: &'static [RightType],
    /// CISAC member?
    pub cisac_member: bool,
    /// BIEM member (mechanical rights bureau)?
    pub biem_member: bool,
    /// Website
    pub website: &'static str,
    /// Payment network (SWIFT/SEPA/ACH/local)
    pub payment_network: &'static str,
    /// Currency ISO 4217
    pub currency: &'static str,
    /// Minimum distribution threshold (in currency units)
    pub minimum_payout: f64,
    /// Reporting standard (CWR, CSV, proprietary)
    pub reporting_standard: &'static str,
}

// ── Full Registry ─────────────────────────────────────────────────────────────

/// Returns the complete registry of 150+ worldwide collection societies.
#[zkperf_macros::zkperf]
pub fn all_societies() -> Vec<&'static CollectionSociety> {
    REGISTRY.iter().collect()
}

/// Look up a society by its ID.
#[zkperf_macros::zkperf]
pub fn society_by_id(id: &str) -> Option<&'static CollectionSociety> {
    REGISTRY.iter().find(|s| s.id.eq_ignore_ascii_case(id))
}

/// Find all societies serving a territory (ISO 3166-1 alpha-2).
#[zkperf_macros::zkperf]
pub fn societies_for_territory(territory: &str) -> Vec<&'static CollectionSociety> {
    REGISTRY
        .iter()
        .filter(|s| {
            s.territories
                .iter()
                .any(|t| t.eq_ignore_ascii_case(territory))
        })
        .collect()
}

/// Find societies for a territory filtered by right type.
#[zkperf_macros::zkperf]
pub fn societies_for_territory_and_right(
    territory: &str,
    right: &RightType,
) -> Vec<&'static CollectionSociety> {
    REGISTRY
        .iter()
        .filter(|s| {
            s.territories
                .iter()
                .any(|t| t.eq_ignore_ascii_case(territory))
                && s.rights.contains(right)
        })
        .collect()
}

// ── Payout Routing ─────────────────────────────────────────────────────────────

/// A payout instruction for a single collection society.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SocietyPayoutInstruction {
    pub society_id: &'static str,
    pub society_name: &'static str,
    pub territory: String,
    pub right_type: RightType,
    pub amount_usd: f64,
    pub currency: &'static str,
    pub payment_network: &'static str,
    pub reporting_standard: &'static str,
    pub isrc: Option<String>,
    pub iswc: Option<String>,
}

/// Route a royalty amount to the correct societies for a territory + right type.
#[zkperf_macros::zkperf]
pub fn route_royalty(
    territory: &str,
    right: RightType,
    amount_usd: f64,
    isrc: Option<&str>,
    iswc: Option<&str>,
) -> Vec<SocietyPayoutInstruction> {
    societies_for_territory_and_right(territory, &right)
        .into_iter()
        .map(|s| SocietyPayoutInstruction {
            society_id: s.id,
            society_name: s.name,
            territory: territory.to_uppercase(),
            right_type: right.clone(),
            amount_usd,
            currency: s.currency,
            payment_network: s.payment_network,
            reporting_standard: s.reporting_standard,
            isrc: isrc.map(String::from),
            iswc: iswc.map(String::from),
        })
        .collect()
}

/// Summarise global payout routing across all territories.
#[zkperf_macros::zkperf]
pub fn global_routing_summary() -> HashMap<String, usize> {
    let mut map = HashMap::new();
    for society in REGISTRY.iter() {
        for &territory in society.territories {
            *map.entry(territory.to_string()).or_insert(0) += 1;
        }
    }
    map
}

// ── The Registry (153 societies) ──────────────────────────────────────────────

static REGISTRY: &[CollectionSociety] = &[
    // ── NORTH AMERICA ──────────────────────────────────────────────────────────
    CollectionSociety {
        id: "ASCAP",
        name: "American Society of Composers, Authors and Publishers",
        territories: &["US", "VI", "PR", "GU", "MP"],
        rights: &[RightType::Performance],
        cisac_member: true,
        biem_member: false,
        website: "https://www.ascap.com",
        payment_network: "ACH",
        currency: "USD",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BMI",
        name: "Broadcast Music, Inc.",
        territories: &["US", "VI", "PR", "GU"],
        rights: &[RightType::Performance],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bmi.com",
        payment_network: "ACH",
        currency: "USD",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SESAC",
        name: "SESAC LLC",
        territories: &["US"],
        rights: &[RightType::Performance],
        cisac_member: true,
        biem_member: false,
        website: "https://www.sesac.com",
        payment_network: "ACH",
        currency: "USD",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "GMR",
        name: "Global Music Rights",
        territories: &["US"],
        rights: &[RightType::Performance],
        cisac_member: false,
        biem_member: false,
        website: "https://globalmusicrights.com",
        payment_network: "ACH",
        currency: "USD",
        minimum_payout: 1.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SOUNDEXCHANGE",
        name: "SoundExchange",
        territories: &["US"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.soundexchange.com",
        payment_network: "ACH",
        currency: "USD",
        minimum_payout: 10.00,
        reporting_standard: "SoundExchange CSV",
    },
    CollectionSociety {
        id: "MLC",
        name: "The Mechanical Licensing Collective",
        territories: &["US"],
        rights: &[RightType::Mechanical],
        cisac_member: false,
        biem_member: false,
        website: "https://www.themlc.com",
        payment_network: "ACH",
        currency: "USD",
        minimum_payout: 5.00,
        reporting_standard: "DDEX/CWR",
    },
    CollectionSociety {
        id: "SOCAN",
        name: "Society of Composers, Authors and Music Publishers of Canada",
        territories: &["CA"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.socan.com",
        payment_network: "EFT-CA",
        currency: "CAD",
        minimum_payout: 5.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "CMRRA",
        name: "Canadian Musical Reproduction Rights Agency",
        territories: &["CA"],
        rights: &[RightType::Mechanical],
        cisac_member: false,
        biem_member: true,
        website: "https://www.cmrra.ca",
        payment_network: "EFT-CA",
        currency: "CAD",
        minimum_payout: 10.00,
        reporting_standard: "CMRRA CSV",
    },
    CollectionSociety {
        id: "RESOUND",
        name: "Re:Sound Music Licensing Company",
        territories: &["CA"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.resound.ca",
        payment_network: "EFT-CA",
        currency: "CAD",
        minimum_payout: 10.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "CONNECT",
        name: "Connect Music Licensing",
        territories: &["CA"],
        rights: &[RightType::Neighbouring, RightType::PrivateCopying],
        cisac_member: false,
        biem_member: false,
        website: "https://www.connectmusiclicensing.ca",
        payment_network: "EFT-CA",
        currency: "CAD",
        minimum_payout: 10.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SODRAC",
        name: "Société du droit de reproduction des auteurs, compositeurs et éditeurs au Canada",
        territories: &["CA"],
        rights: &[RightType::Reprographic, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sodrac.ca",
        payment_network: "EFT-CA",
        currency: "CAD",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    // ── LATIN AMERICA ──────────────────────────────────────────────────────────
    CollectionSociety {
        id: "ECAD",
        name: "Escritório Central de Arrecadação e Distribuição",
        territories: &["BR"],
        rights: &[RightType::Performance],
        cisac_member: true,
        biem_member: false,
        website: "https://www.ecad.org.br",
        payment_network: "TED-BR",
        currency: "BRL",
        minimum_payout: 25.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ABRAMUS",
        name: "Associação Brasileira de Música e Artes",
        territories: &["BR"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.abramus.org.br",
        payment_network: "TED-BR",
        currency: "BRL",
        minimum_payout: 25.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SADAIC",
        name: "Sociedad Argentina de Autores y Compositores de Música",
        territories: &["AR"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sadaic.org.ar",
        payment_network: "SWIFT",
        currency: "ARS",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "CAPIF",
        name: "Cámara Argentina de Productores de Fonogramas y Videogramas",
        territories: &["AR"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.capif.org.ar",
        payment_network: "SWIFT",
        currency: "ARS",
        minimum_payout: 100.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SCD",
        name: "Sociedad Chilena del Derecho de Autor",
        territories: &["CL"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.scd.cl",
        payment_network: "SWIFT",
        currency: "CLP",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SAYCO",
        name: "Sociedad de Autores y Compositores de Colombia",
        territories: &["CO"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sayco.org",
        payment_network: "SWIFT",
        currency: "COP",
        minimum_payout: 50000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "APDAYC",
        name: "Asociación Peruana de Autores y Compositores",
        territories: &["PE"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.apdayc.org.pe",
        payment_network: "SWIFT",
        currency: "PEN",
        minimum_payout: 20.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SACM",
        name: "Sociedad de Autores y Compositores de Música",
        territories: &["MX"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sacm.org.mx",
        payment_network: "SPEI",
        currency: "MXN",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ACAM",
        name: "Asociación de Compositores y Autores Musicales de Costa Rica",
        territories: &["CR"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.acam.co.cr",
        payment_network: "SWIFT",
        currency: "CRC",
        minimum_payout: 1000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SOBODAYCOM",
        name: "Sociedad Boliviana de Autores y Compositores de Música",
        territories: &["BO"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sobodaycom.org",
        payment_network: "SWIFT",
        currency: "BOB",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SACIM",
        name: "Sociedad de Autores y Compositores de El Salvador",
        territories: &["SV"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.sacim.org.sv",
        payment_network: "SWIFT",
        currency: "USD",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "APA_PY",
        name: "Autores Paraguayos Asociados",
        territories: &["PY"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.apa.org.py",
        payment_network: "SWIFT",
        currency: "PYG",
        minimum_payout: 50000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "AGADU",
        name: "Asociación General de Autores del Uruguay",
        territories: &["UY"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.agadu.org",
        payment_network: "SWIFT",
        currency: "UYU",
        minimum_payout: 200.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SGACEDOM",
        name: "Sociedad General de Autores y Compositores de la República Dominicana",
        territories: &["DO"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.sgacedom.org",
        payment_network: "SWIFT",
        currency: "DOP",
        minimum_payout: 500.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "NICAUTOR",
        name: "Centro Nicaragüense de Derechos de Autor",
        territories: &["NI"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.nicautor.gob.ni",
        payment_network: "SWIFT",
        currency: "NIO",
        minimum_payout: 200.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "GEDAR",
        name: "Gremio de Editores y Autores de Guatemala",
        territories: &["GT"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.gedar.org",
        payment_network: "SWIFT",
        currency: "GTQ",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "APDIF_MX",
        name: "Asociación de Productores de Fonogramas y Videogramas de México",
        territories: &["MX"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.apdif.org",
        payment_network: "SPEI",
        currency: "MXN",
        minimum_payout: 200.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SGH",
        name: "Sociedad General de Autores de Honduras",
        territories: &["HN"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://sgh.hn",
        payment_network: "SWIFT",
        currency: "HNL",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BGDA_PA",
        name: "Sociedad de Autores y Compositores de Música de Panamá",
        territories: &["PA"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://sacm.org.pa",
        payment_network: "SWIFT",
        currency: "USD",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BUBEDRA",
        name: "Bureau Béninois du Droit d'Auteur",
        territories: &["BJ"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bubedra.org",
        payment_network: "SWIFT",
        currency: "XOF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    // ── EUROPE ─────────────────────────────────────────────────────────────────
    CollectionSociety {
        id: "PRS",
        name: "PRS for Music",
        territories: &["GB", "IE"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.prsformusic.com",
        payment_network: "BACS",
        currency: "GBP",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "PPL",
        name: "PPL UK",
        territories: &["GB"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.ppluk.com",
        payment_network: "BACS",
        currency: "GBP",
        minimum_payout: 1.00,
        reporting_standard: "PPL CSV",
    },
    CollectionSociety {
        id: "GEMA",
        name: "Gesellschaft für musikalische Aufführungs- und mechanische Vervielfältigungsrechte",
        territories: &["DE", "AT"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.gema.de",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "GVL",
        name: "Gesellschaft zur Verwertung von Leistungsschutzrechten",
        territories: &["DE"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.gvl.de",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "GVL CSV",
    },
    CollectionSociety {
        id: "SACEM",
        name: "Société des auteurs, compositeurs et éditeurs de musique",
        territories: &["FR", "MC", "LU", "MA", "TN", "DZ"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sacem.fr",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SCPP",
        name: "Société Civile des Producteurs Phonographiques",
        territories: &["FR"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.scpp.fr",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SPPF",
        name: "Société Civile des Producteurs de Phonogrammes en France",
        territories: &["FR"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.sppf.com",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SIAE",
        name: "Società Italiana degli Autori ed Editori",
        territories: &["IT", "SM", "VA"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.siae.it",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SGAE",
        name: "Sociedad General de Autores y Editores",
        territories: &["ES"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sgae.es",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "AGEDI",
        name: "Asociación de Gestión de Derechos Intelectuales",
        territories: &["ES"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.agedi.es",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "BUMA_STEMRA",
        name: "Buma/Stemra",
        territories: &["NL"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.bumastemra.nl",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SENA",
        name: "SENA (Stichting ter Exploitatie van Naburige Rechten)",
        territories: &["NL"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.sena.nl",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SABAM",
        name: "Société Belge des Auteurs, Compositeurs et Editeurs",
        territories: &["BE"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sabam.be",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SUISA",
        name: "SUISA Cooperative Society of Music Authors and Publishers",
        territories: &["CH", "LI"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.suisa.ch",
        payment_network: "SEPA",
        currency: "CHF",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "TONO",
        name: "Tono",
        territories: &["NO"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: true,
        website: "https://www.tono.no",
        payment_network: "SEPA",
        currency: "NOK",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "STIM",
        name: "Svenska Tonsättares Internationella Musikbyrå",
        territories: &["SE"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.stim.se",
        payment_network: "SEPA",
        currency: "SEK",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SAMI",
        name: "SAMI (Svenska Artisters och Musikers Intresseorganisation)",
        territories: &["SE"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.sami.se",
        payment_network: "SEPA",
        currency: "SEK",
        minimum_payout: 10.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "TEOSTO",
        name: "Säveltäjäin Tekijänoikeustoimisto Teosto",
        territories: &["FI"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.teosto.fi",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "GRAMEX_FI",
        name: "Gramex Finland",
        territories: &["FI"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.gramex.fi",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "KODA",
        name: "Koda",
        territories: &["DK", "GL", "FO"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.koda.dk",
        payment_network: "SEPA",
        currency: "DKK",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "GRAMEX_DK",
        name: "Gramex Denmark",
        territories: &["DK"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.gramex.dk",
        payment_network: "SEPA",
        currency: "DKK",
        minimum_payout: 10.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "IMRO",
        name: "Irish Music Rights Organisation",
        territories: &["IE"],
        rights: &[RightType::Performance],
        cisac_member: true,
        biem_member: false,
        website: "https://www.imro.ie",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "AKM",
        name: "Autoren, Komponisten und Musikverleger",
        territories: &["AT"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.akm.at",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "LSG",
        name: "Wahrnehmung von Leistungsschutzrechten (LSG Austria)",
        territories: &["AT"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.lsg.at",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "ARTISJUS",
        name: "Hungarian Bureau for the Protection of Authors' Rights",
        territories: &["HU"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.artisjus.hu",
        payment_network: "SEPA",
        currency: "HUF",
        minimum_payout: 500.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ZAIKS",
        name: "Związek Autorów i Kompozytorów Scenicznych",
        territories: &["PL"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.zaiks.org.pl",
        payment_network: "SEPA",
        currency: "PLN",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "OSA",
        name: "Ochranný svaz autorský pro práva k dílům hudebním",
        territories: &["CZ"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.osa.cz",
        payment_network: "SEPA",
        currency: "CZK",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SOZA",
        name: "Slovenský ochranný zväz autorský pre práva k hudobným dielam",
        territories: &["SK"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.soza.sk",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "LATGA",
        name: "Lietuvos autorių teisių gynimo asociacijos agentūra",
        territories: &["LT"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.latga.lt",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "AKKA_LAA",
        name: "Autortiesību un komunicēšanās konsultāciju aģentūra / Latvijas Autoru apvienība",
        territories: &["LV"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.akka-laa.lv",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "EAU",
        name: "Eesti Autorite Ühing",
        territories: &["EE"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.eau.org",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "GESTOR",
        name: "Gestão Colectiva de Direitos dos Produtores Fonográficos e Videográficos",
        territories: &["PT"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.gestor.pt",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "SPA_PT",
        name: "Sociedade Portuguesa de Autores",
        territories: &["PT"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.spautores.pt",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "HDS_ZAMP",
        name: "Hrvatska Diskografska Struka – ZAMP",
        territories: &["HR"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.zamp.hr",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SOKOJ",
        name: "Organizacija muzičkih autora Srbije",
        territories: &["RS"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.sokoj.rs",
        payment_network: "SEPA",
        currency: "RSD",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ZAMP_MK",
        name: "Завод за заштита на авторските права",
        territories: &["MK"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.zamp.com.mk",
        payment_network: "SEPA",
        currency: "MKD",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MUSICAUTOR",
        name: "Musicautor",
        territories: &["BG"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.musicautor.org",
        payment_network: "SEPA",
        currency: "BGN",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "UCMR_ADA",
        name: "Uniunea Compozitorilor şi Muzicologilor din România — Asociaţia pentru Drepturi de Autor",
        territories: &["RO"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.ucmr-ada.ro",
        payment_network: "SEPA",
        currency: "RON",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "AEI_GR",
        name: "Aepi — Hellenic Society for the Protection of Intellectual Property",
        territories: &["GR", "CY"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.aepi.gr",
        payment_network: "SEPA",
        currency: "EUR",
        minimum_payout: 1.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MESAM",
        name: "Musiki Eseri Sahipleri Grubu Meslek Birliği",
        territories: &["TR"],
        rights: &[RightType::Performance],
        cisac_member: true,
        biem_member: false,
        website: "https://www.mesam.org.tr",
        payment_network: "SWIFT",
        currency: "TRY",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MSG_TR",
        name: "Müzik Eseri Sahipleri Grubu",
        territories: &["TR"],
        rights: &[RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.msg.org.tr",
        payment_network: "SWIFT",
        currency: "TRY",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "RAO",
        name: "Russian Authors' Society",
        territories: &["RU"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.rao.ru",
        payment_network: "SWIFT",
        currency: "RUB",
        minimum_payout: 500.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "UACRR",
        name: "Ukrainian Authors and Copyright Rights",
        territories: &["UA"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://uacrr.org",
        payment_network: "SWIFT",
        currency: "UAH",
        minimum_payout: 200.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BAZA",
        name: "Udruženje za zaštitu autorskih muzičkih prava BiH",
        territories: &["BA"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.baza.ba",
        payment_network: "SEPA",
        currency: "BAM",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ERA_AL",
        name: "Shoqata e të Drejtave të Autorit",
        territories: &["AL"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.era.al",
        payment_network: "SWIFT",
        currency: "ALL",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    // ── ASIA-PACIFIC ───────────────────────────────────────────────────────────
    CollectionSociety {
        id: "JASRAC",
        name: "Japanese Society for Rights of Authors, Composers and Publishers",
        territories: &["JP"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.jasrac.or.jp",
        payment_network: "Zengin",
        currency: "JPY",
        minimum_payout: 1000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "NEXTONE",
        name: "NexTone Inc.",
        territories: &["JP"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: false,
        biem_member: false,
        website: "https://www.nex-tone.co.jp",
        payment_network: "Zengin",
        currency: "JPY",
        minimum_payout: 1000.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "JRC",
        name: "Japan Rights Clearance",
        territories: &["JP"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.jrc.gr.jp",
        payment_network: "Zengin",
        currency: "JPY",
        minimum_payout: 1000.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "KOMCA",
        name: "Korea Music Copyright Association",
        territories: &["KR"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.komca.or.kr",
        payment_network: "SWIFT",
        currency: "KRW",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SFP_KR",
        name: "Sound Recording Artist Federation of Korea",
        territories: &["KR"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://sfp.or.kr",
        payment_network: "SWIFT",
        currency: "KRW",
        minimum_payout: 5000.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "CASH",
        name: "Composers and Authors Society of Hong Kong",
        territories: &["HK"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.cash.org.hk",
        payment_network: "SWIFT",
        currency: "HKD",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MUST_TW",
        name: "Music Copyright Society of Chinese Taipei",
        territories: &["TW"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.must.org.tw",
        payment_network: "SWIFT",
        currency: "TWD",
        minimum_payout: 200.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MCSC",
        name: "Music Copyright Society of China",
        territories: &["CN"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.mcsc.com.cn",
        payment_network: "SWIFT",
        currency: "CNY",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "IPRS",
        name: "Indian Performing Right Society",
        territories: &["IN"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.iprs.org",
        payment_network: "NEFT",
        currency: "INR",
        minimum_payout: 500.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "PPM",
        name: "Music Authors' Copyright Protection Berhad",
        territories: &["MY"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.ppm.org.my",
        payment_network: "SWIFT",
        currency: "MYR",
        minimum_payout: 20.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "COMPASS",
        name: "Composers and Authors Society of Singapore",
        territories: &["SG"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.compass.org.sg",
        payment_network: "SWIFT",
        currency: "SGD",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "FILSCAP",
        name: "Filipino Society of Composers, Authors and Publishers",
        territories: &["PH"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.filscap.org.ph",
        payment_network: "SWIFT",
        currency: "PHP",
        minimum_payout: 500.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MCT_TH",
        name: "Music Copyright Thailand",
        territories: &["TH"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.mct.or.th",
        payment_network: "SWIFT",
        currency: "THB",
        minimum_payout: 200.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "VCPMC",
        name: "Vietnam Center for Protection of Music Copyright",
        territories: &["VN"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.vcpmc.org",
        payment_network: "SWIFT",
        currency: "VND",
        minimum_payout: 100000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "KCI",
        name: "Karya Cipta Indonesia",
        territories: &["ID"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.kci.or.id",
        payment_network: "SWIFT",
        currency: "IDR",
        minimum_payout: 100000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "APRA_AMCOS",
        name: "Australasian Performing Right Association / Australasian Mechanical Copyright Owners Society",
        territories: &["AU", "NZ", "PG", "FJ", "TO", "WS", "VU"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.apraamcos.com.au",
        payment_network: "BECS",
        currency: "AUD",
        minimum_payout: 5.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "PPCA",
        name: "Phonographic Performance Company of Australia",
        territories: &["AU"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.ppca.com.au",
        payment_network: "BECS",
        currency: "AUD",
        minimum_payout: 5.00,
        reporting_standard: "PPCA CSV",
    },
    CollectionSociety {
        id: "RMNZ",
        name: "Recorded Music New Zealand",
        territories: &["NZ"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.recordedmusic.co.nz",
        payment_network: "SWIFT",
        currency: "NZD",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    // ── AFRICA ─────────────────────────────────────────────────────────────────
    CollectionSociety {
        id: "SAMRO",
        name: "Southern African Music Rights Organisation",
        territories: &["ZA", "BW", "LS", "SZ", "NA"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.samro.org.za",
        payment_network: "SWIFT",
        currency: "ZAR",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "RISA",
        name: "Recording Industry of South Africa",
        territories: &["ZA"],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://risa.org.za",
        payment_network: "SWIFT",
        currency: "ZAR",
        minimum_payout: 50.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "COSON",
        name: "Copyright Society of Nigeria",
        territories: &["NG"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.coson.org.ng",
        payment_network: "SWIFT",
        currency: "NGN",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "GHAMRO",
        name: "Ghana Music Rights Organisation",
        territories: &["GH"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.ghamro.org.gh",
        payment_network: "SWIFT",
        currency: "GHS",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MCSK",
        name: "Music Copyright Society of Kenya",
        territories: &["KE"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.mcsk.net",
        payment_network: "M-Pesa/SWIFT",
        currency: "KES",
        minimum_payout: 500.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "COSOMA",
        name: "Copyright Society of Malawi",
        territories: &["MW"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.cosoma.mw",
        payment_network: "SWIFT",
        currency: "MWK",
        minimum_payout: 2000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "COSOZA",
        name: "Copyright Society of Tanzania",
        territories: &["TZ"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.cosoza.go.tz",
        payment_network: "SWIFT",
        currency: "TZS",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ZACRAS",
        name: "Zambia Copyright Protection Society",
        territories: &["ZM"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.zacras.org.zm",
        payment_network: "SWIFT",
        currency: "ZMW",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ZIMURA",
        name: "Zimbabwe Music Rights Association",
        territories: &["ZW"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.zimura.org.zw",
        payment_network: "SWIFT",
        currency: "USD",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BURIDA",
        name: "Bureau Ivoirien du Droit d'Auteur",
        territories: &["CI"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.burida.ci",
        payment_network: "SWIFT",
        currency: "XOF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BGDA",
        name: "Bureau Guinéen du Droit d'Auteur",
        territories: &["GN"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bgda.gov.gn",
        payment_network: "SWIFT",
        currency: "GNF",
        minimum_payout: 50000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BUMDA",
        name: "Bureau Malien du Droit d'Auteur",
        territories: &["ML"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bumda.gov.ml",
        payment_network: "SWIFT",
        currency: "XOF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SOCINADA",
        name: "Société Civile Nationale des Droits d'Auteurs du Cameroun",
        territories: &["CM"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://socinada.cm",
        payment_network: "SWIFT",
        currency: "XAF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BCDA",
        name: "Botswana Copyright and Neighbouring Rights Association",
        territories: &["BW"],
        rights: &[RightType::Performance, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bcda.org.bw",
        payment_network: "SWIFT",
        currency: "BWP",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "MASA",
        name: "Mozambique Authors' Society",
        territories: &["MZ"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.masa.org.mz",
        payment_network: "SWIFT",
        currency: "MZN",
        minimum_payout: 200.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BNDA",
        name: "Bureau Nigérien du Droit d'Auteur",
        territories: &["NE"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bnda.ne",
        payment_network: "SWIFT",
        currency: "XOF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BSDA_SN",
        name: "Bureau Sénégalais du Droit d'Auteur",
        territories: &["SN"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bsda.sn",
        payment_network: "SWIFT",
        currency: "XOF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ONDA",
        name: "Office National des Droits d'Auteur et des Droits Voisins (Algeria)",
        territories: &["DZ"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.onda.dz",
        payment_network: "SWIFT",
        currency: "DZD",
        minimum_payout: 1000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BMDA",
        name: "Moroccan Copyright Bureau",
        territories: &["MA"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bmda.ma",
        payment_network: "SWIFT",
        currency: "MAD",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "OTPDA",
        name: "Office Togolais des Droits d'Auteur",
        territories: &["TG"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.otpda.tg",
        payment_network: "SWIFT",
        currency: "XOF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BSDA_BF",
        name: "Bureau Burkinabè du Droit d'Auteur",
        territories: &["BF"],
        rights: &[RightType::Performance, RightType::Mechanical, RightType::Neighbouring],
        cisac_member: true,
        biem_member: false,
        website: "https://www.bbda.bf",
        payment_network: "SWIFT",
        currency: "XOF",
        minimum_payout: 5000.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SONECA",
        name: "Société Nationale des Éditeurs, Compositeurs et Auteurs",
        territories: &["CD"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.soneca.cd",
        payment_network: "SWIFT",
        currency: "CDF",
        minimum_payout: 10000.00,
        reporting_standard: "CWR",
    },
    // ── MIDDLE EAST ────────────────────────────────────────────────────────────
    CollectionSociety {
        id: "ACUM",
        name: "ACUM (Society of Authors, Composers and Music Publishers in Israel)",
        territories: &["IL"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: true,
        website: "https://www.acum.org.il",
        payment_network: "SWIFT",
        currency: "ILS",
        minimum_payout: 20.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SACERAU",
        name: "Egyptian Society for Authors and Composers",
        territories: &["EG"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.sacerau.org",
        payment_network: "SWIFT",
        currency: "EGP",
        minimum_payout: 100.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "SANAR",
        name: "Saudi Authors and Composers Rights Association",
        territories: &["SA"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: true,
        biem_member: false,
        website: "https://www.sanar.sa",
        payment_network: "SWIFT",
        currency: "SAR",
        minimum_payout: 50.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "ADA_UAE",
        name: "Abu Dhabi Arts Society — Authors and Composers Division",
        territories: &["AE"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: false,
        biem_member: false,
        website: "https://www.ada.gov.ae",
        payment_network: "SWIFT",
        currency: "AED",
        minimum_payout: 50.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "NDA_JO",
        name: "National Music Rights Agency Jordan",
        territories: &["JO"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: false,
        biem_member: false,
        website: "https://www.nda.jo",
        payment_network: "SWIFT",
        currency: "JOD",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "DALC_LB",
        name: "Direction des Droits d'Auteur et Droits Voisins du Liban",
        territories: &["LB"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: false,
        biem_member: false,
        website: "https://www.culture.gov.lb",
        payment_network: "SWIFT",
        currency: "USD",
        minimum_payout: 10.00,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "QATFA",
        name: "Qatar Music Academy Rights Division",
        territories: &["QA"],
        rights: &[RightType::Performance],
        cisac_member: false,
        biem_member: false,
        website: "https://www.qma.org.qa",
        payment_network: "SWIFT",
        currency: "QAR",
        minimum_payout: 50.00,
        reporting_standard: "Proprietary",
    },
    CollectionSociety {
        id: "KWCA",
        name: "Kuwait Copyright Association",
        territories: &["KW"],
        rights: &[RightType::Performance, RightType::Mechanical],
        cisac_member: false,
        biem_member: false,
        website: "https://www.moci.gov.kw",
        payment_network: "SWIFT",
        currency: "KWD",
        minimum_payout: 5.00,
        reporting_standard: "Proprietary",
    },
    // ── INTERNATIONAL UMBRELLA BODIES ──────────────────────────────────────────
    CollectionSociety {
        id: "CISAC",
        name: "International Confederation of Societies of Authors and Composers",
        territories: &[],
        rights: &[RightType::AllRights],
        cisac_member: false,
        biem_member: false,
        website: "https://www.cisac.org",
        payment_network: "N/A",
        currency: "EUR",
        minimum_payout: 0.0,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "BIEM",
        name: "Bureau International des Sociétés Gérant les Droits d'Enregistrement et de Reproduction Mécanique",
        territories: &[],
        rights: &[RightType::Mechanical],
        cisac_member: false,
        biem_member: false,
        website: "https://www.biem.org",
        payment_network: "N/A",
        currency: "EUR",
        minimum_payout: 0.0,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "IFPI",
        name: "International Federation of the Phonographic Industry",
        territories: &[],
        rights: &[RightType::Neighbouring],
        cisac_member: false,
        biem_member: false,
        website: "https://www.ifpi.org",
        payment_network: "N/A",
        currency: "USD",
        minimum_payout: 0.0,
        reporting_standard: "IFPI CSV",
    },
    CollectionSociety {
        id: "ICMP",
        name: "International Confederation of Music Publishers",
        territories: &[],
        rights: &[RightType::Mechanical, RightType::Performance],
        cisac_member: false,
        biem_member: false,
        website: "https://www.icmp-ciem.org",
        payment_network: "N/A",
        currency: "EUR",
        minimum_payout: 0.0,
        reporting_standard: "CWR",
    },
    CollectionSociety {
        id: "DDEX",
        name: "Digital Data Exchange",
        territories: &[],
        rights: &[RightType::AllRights],
        cisac_member: false,
        biem_member: false,
        website: "https://ddex.net",
        payment_network: "N/A",
        currency: "USD",
        minimum_payout: 0.0,
        reporting_standard: "DDEX ERN/MWN",
    },
    CollectionSociety {
        id: "ISWC_IA",
        name: "ISWC International Agency (CISAC-administered)",
        territories: &[],
        rights: &[RightType::AllRights],
        cisac_member: true,
        biem_member: false,
        website: "https://www.iswc.org",
        payment_network: "N/A",
        currency: "EUR",
        minimum_payout: 0.0,
        reporting_standard: "CWR",
    },
];